stm32cube: stm32h7: eth: avoid descriptor leak with enabled timestamping
zephyrproject-rtos/hal_stm32 pull request #116
Opened 2021-09-16 06:13 UTC by alsrgv

Ethernet HAL configures interrupts to be received upon filling every
RX descriptor. When timestamping is enabled, application needs to
process both normal and context descriptors, but there is a race
condition in HAL_ETH_IsRxDataAvailable() that might miss context
descriptor, effectively leaking it.

This change introduces spinlock to wait for context descriptor if
normal context indicates it will be available.

Signed-off-by: Alex Sergeev <asergeev@carbonrobotics.com>

2021-09-16 06:15 UTC, alsrgv commented
@erwango @FRASTM, we've found this issue with STM32H7 HAL, what's the best way to get it fixed? Here's the proposed PR with the fix.

2021-11-04 14:25 UTC, erwango commented
@alsrgv Thanks for raising this.
Would you mind raising it directly to https://github.com/STMicroelectronics/STM32CubeH7 repo ?
If error is acknowledged by H7 experts, we'll be able to merge the proposed fix, waiting the official delivery to be available.

2021-11-24 10:29 UTC, erwango requested changes
@alsrgv Thanks for proposing this fix.
Point is acknowledged by STM32Cube team, so let's integrate it, waiting for an official fix.

2021-11-24 10:29 UTC, erwango commented on stm32cube/stm32h7xx/drivers/src/stm32h7xx_hal_eth.c
> +        while(READ_BIT(dmarxdesc->DESC3, ETH_DMARXNDESCWBF_OWN) != (uint32_t)RESET || READ_BIT(dmarxdesc->DESC3, ETH_DMARXNDESCWBF_CTXT) == (uint32_t)RESET)
Nit: Please fix the long line

2021-11-24 10:29 UTC, erwango commented on stm32cube/stm32h7xx/README
> +   *stm32h7xx_hal_eth.c: Fix context descriptor leak
```suggestion
   *Fix context descriptor leak
    - Impacted file: stm32h7xx_hal_eth.c
    - Internal reference: Not available. Will be fixed as part of a new eth hal implementation
```

2021-11-25 00:44 UTC, alsrgv commented
Great, thanks for feedback!  Updated.

2021-11-25 07:53 UTC, erwango approved these changes

2021-11-25 16:17 UTC, erwango commented
@alsrgv Can you rebase this change ? A missing commit available on top of the branch is creating issues in CI on the main repo.

2021-11-25 20:46 UTC, alsrgv commented
@erwango, done.

2021-12-06 19:45 UTC, alsrgv commented
@erwango, any updates on this?

2021-12-08 07:06 UTC, merged