Lcd pins
zephyrproject-rtos/hal_stm32 pull request #121
Opened 2021-10-31 16:16 UTC by mass-anis

added the lcd pins to stm32-pinctrl

2021-11-02 15:02 UTC, gmarull requested changes
Please check contribution guidelines to format commit messages accordingly.

2021-11-02 15:02 UTC, gmarull commented on scripts/genpinctrl/stm32-pinctrl-config.yaml
> +  match: "^LCD(?:\\d+)?_SEG\\d+$"
please use a single entry, as e.g.

```
^QUADSPI_(?:CLK|NCS|BK1_NCS|BK1_IO[0-3]|BK2_NCS|BK2_IO[0-3])$
```

2021-11-02 15:02 UTC, gmarull commented on dts/README.md
> +   76cea512bdcafd6be002393400ebd925aec90531
if using another version, first run the generator with the new version and then add LCD support.

2021-11-02 15:04 UTC, erwango requested changes
Please update commit messages to stick with main repo rules.

2021-11-02 15:04 UTC, erwango commented on dts/README.md
> +   76cea512bdcafd6be002393400ebd925aec90531
Please don't modify SHA1 in current PR.

2021-11-08 09:38 UTC, gmarull commented on scripts/genpinctrl/stm32-pinctrl-config.yaml
> +  match: "^LCD\\d*_(?:SEG|COM|VLCD)?\\d*$"
Are there any `LCD0_`, `LCD1_`, etc.?

2021-11-08 16:02 UTC, gmarull commented on scripts/genpinctrl/stm32-pinctrl-config.yaml
> +  match: "^LCD\\d*_(?:SEG|COM|VLCD)?\\d*$"
does, e.g. `LCD0_SEGn` exist?

2023-03-01 13:58 UTC, erwango commented
Stale, closing

2023-03-01 13:58 UTC, closed without merging