STM32Cube packages update for V3.1.0
zephyrproject-rtos/hal_stm32 pull request #135
Opened 2022-03-15 10:15 UTC by erwango

New batch of stm32cube package updates:

- update stm32l4 to cube version V1.17.1
- update stm32wb to cube version V1.13.2 (including hci lib)
- update stm32f4 to cube version V1.27.0
- update stm32u5 to cube version V1.1.0
- update stm32g4 to cube version V1.5.0
- update stm32h7 to cube version V1.10.0
- update stm32f7 to cube version V1.16.2

2022-03-18 15:52 UTC, erwango commented
@gmarull Would you mind having a look at the python 3.7/8 tests?
On my end 3.8 is working, seems to be GH action specific.

2022-03-18 17:01 UTC, gmarull commented
> @gmarull Would you mind having a look at the python 3.7/8 tests? On my end 3.8 is working, seems to be GH action specific.

@erwango https://github.com/zephyrproject-rtos/hal_stm32/pull/136

2022-03-22 08:21 UTC, erwango commented
Tests results:
```
Failed tests:
   (verdicts: T/p: Passed, F/f: Failed, t:timeout)
   samples/modules/canopennode/sample.modules.canopennode, nucleo_g474re
   samples/modules/canopennode/sample.modules.canopennode, nucleo_h743zi
   samples/modules/canopennode/sample.modules.canopennode.no_storage, nucleo_g474re
   samples/modules/canopennode/sample.modules.canopennode.no_storage, nucleo_h743zi
   samples/subsys/nvs/sample.nvs.basic, disco_l475_iot1
   samples/subsys/task_wdt/sample.subsys.task_wdt, nucleo_f091rc
   samples/subsys/task_wdt/sample.subsys.task_wdt, nucleo_f429zi
   samples/subsys/task_wdt/sample.subsys.task_wdt, nucleo_l073rz
   samples/subsys/task_wdt/sample.subsys.task_wdt, nucleo_l152re
   tests/drivers/flash/drivers.flash.stm32, nucleo_h743zi
   tests/kernel/mem_protect/stack_random/kernel.memory_protection.stack_random, nucleo_l152re (instable: ppffffppppppppppppppppppppppppppppppp)
   tests/lib/cmsis_dsp/filtering/libraries.cmsis_dsp.filtering.misc.fpu, b_u585i_iot02a (instable: ppptptppptpppptppppppptpptppppppppppt)
   tests/lib/cmsis_dsp/filtering/libraries.cmsis_dsp.filtering.misc.fpu, disco_l475_iot1 (instable: pppppptppppppppppppfptpppppppppppttpp)
   tests/subsys/canbus/isotp/implementation/subsys.canbus.isotp.implementation, nucleo_g474re

Recently Skipped:
   tests/kernel/threads/dynamic_thread/kernel.threads.dynamic, nucleo_l073rz

Total: 14 test(s) failed out of 4344 tests run
       4330 test(s) passed
       0 regression(s) on stable test
Recently skipped: 1
```

Which is same as current master.

2022-03-30 08:43 UTC, ABOSTM requested changes

2022-03-30 09:39 UTC, ABOSTM approved these changes

2022-03-31 09:58 UTC, FRASTM approved these changes

2022-03-31 11:14 UTC, merged