dts: st: regenerate pinctrl files with CubeMX 6.7.0 release
zephyrproject-rtos/hal_stm32 pull request #164
Opened 2023-03-03 07:34 UTC by benjaminbjornsson

We're currently using the CubeMX 6.5.0 release which causes some problems when generating pinctrl for STM32C0. Updating to CubeMX 6.7.0 solves this problem.

2023-03-03 07:46 UTC, erwango commented
@gautierg-st please review

2023-03-03 14:27 UTC, gautierg-st requested changes

2023-03-03 14:27 UTC, gautierg-st commented on dts/st/f0/stm32f030r8tx-pinctrl.dtsi
> +				pinmux = <STM32_PINMUX('C', 8, AF1)>;
Previous code was correct. The datasheet agrees that it is AF0, and not AF1.
The issue has been raised on CubeMX teams side.

2023-03-05 19:47 UTC, benjaminbjornsson commented
We'll wait for next release.

2023-03-05 19:47 UTC, closed without merging