drivers: STM32U5 : ADC_LL : fix : fixed ADC4 single channel sampling
zephyrproject-rtos/hal_stm32 pull request #167
Opened 2023-03-17 13:37 UTC by herman-dren

If read 2 different channels in turn, CHSELR register will content two channels. need erase register before write a new channel

2023-03-21 10:30 UTC, FRASTM requested changes

2023-03-21 10:30 UTC, FRASTM commented on stm32cube/stm32u5xx/drivers/include/stm32u5xx_ll_adc.h
> +    MODIFY_REG(ADCx->CHSELR, ADC_CHSELR_CHSEL,SequencerNbRanks);
```suggestion
    MODIFY_REG(ADCx->CHSELR, ADC_CHSELR_CHSEL, SequencerNbRanks);
```

2023-03-21 14:05 UTC, erwango requested changes
Please don't add fix commits.
Apply changes inside the initial commit, also please see https://docs.zephyrproject.org/latest/contribute/guidelines.html about commit messages and signed-off.

Then I stand on my initial remark, please submit the change on official STM32 package first.

2024-05-03 15:12 UTC, erwango commented
I'm closing this PR due to inactivity. Please reopen if required.

2024-05-03 15:12 UTC, closed without merging