STM32Cube packages update
zephyrproject-rtos/hal_stm32 pull request #168
Opened 2023-04-04 13:38 UTC by gautierg-st

New batch of stm32cube package updates:

- update stm32f0 to cube version V1.11.4
- update stm32f3 to cube version V1.11.4
- update stm32l0 to cube version V1.12.2
- update stm32u5 to cube version V1.2.0
- update stm32wb to cube version V1.16.0

2023-04-04 13:57 UTC, erwango requested changes

2023-04-04 13:57 UTC, erwango commented on stm32cube/stm32f3xx/drivers/include/Legacy/stm32f3xx_hal_can_legacy.h
> +  * If no LICENSE file comes with this software, it is provided AS-IS.
Ditto

2023-04-04 13:57 UTC, erwango commented on stm32cube/stm32l0xx/drivers/include/stm32l0xx_hal.h
> +  * If no LICENSE file comes with this software, it is provided AS-IS.
Ditto

2023-04-04 13:57 UTC, erwango commented on lib/stm32wb/hci/README
> +--> please check that the following list
Remove this line

2023-04-04 15:01 UTC, gautierg-st commented on stm32cube/stm32f0xx/drivers/include/Legacy/stm32f0xx_hal_can_legacy.h
> +  * If no LICENSE file comes with this software, it is provided AS-IS.
Done

2023-04-04 15:02 UTC, gautierg-st commented on lib/stm32wb/hci/README
> +         *  Change payload size of several structure defined in tl.h from 255
Done

2023-04-04 15:02 UTC, gautierg-st commented on lib/stm32wb/hci/README
> +--> please check that the following list
Done

2023-04-04 15:12 UTC, erwango requested changes

2023-04-04 15:12 UTC, erwango commented on lib/stm32wb/hci/app_conf.h
> -#define CFG_BLE_OPTIONS  (SHCI_C2_BLE_INIT_OPTIONS_LL_ONLY | SHCI_C2_BLE_INIT_OPTIONS_WITH_SVC_CHANGE_DESC | SHCI_C2_BLE_INIT_OPTIONS_DEVICE_NAME_RW | SHCI_C2_BLE_INIT_OPTIONS_NO_EXT_ADV | SHCI_C2_BL
/* Z-WB-3 */ deleted

2023-04-05 07:49 UTC, gautierg-st commented on lib/stm32wb/hci/app_conf.h
> -#define CFG_BLE_OPTIONS  (SHCI_C2_BLE_INIT_OPTIONS_LL_ONLY | SHCI_C2_BLE_INIT_OPTIONS_WITH_SVC_CHANGE_DESC | SHCI_C2_BLE_INIT_OPTIONS_DEVICE_NAME_RW | SHCI_C2_BLE_INIT_OPTIONS_NO_EXT_ADV | SHCI_C2_BL
Fixed

2023-04-05 08:19 UTC, erwango approved these changes

2023-04-05 08:54 UTC, gautierg-st commented on lib/stm32wb/hci/app_conf.h
> +  #define CFG_BLE_LS_SOURCE  (SHCI_C2_BLE_INIT_CFG_BLE_LS_NOCALIB | SHCI_C2_BLE_INIT_CFG_BLE_LS_OTHER_DEV | SHCI_C2_BLE_INIT_CFG_BLE_LS_CLK_LSE)
Updated in PR https://github.com/zephyrproject-rtos/zephyr/pull/56530

2023-04-14 14:25 UTC, merged