scripts: genpinctrl: add support for FSMC pins
zephyrproject-rtos/hal_stm32 pull request #173
Opened 2023-05-08 19:57 UTC by douardda

FSMC and FMC are very similar, but FSMC pins in STM32_open_pin_data are identified  as FSMC_xxx, so they are not included in generated pinctrl dts files.

This just modify the regex in the stm32-pinctrl-config.yaml file to match "FSMC" in addition to "FMC".

If accepted, dtsi files will have to be regenerated in a following PR.

2023-05-17 16:29 UTC, douardda commented
Any chance to have this PR reviewed?

2023-05-22 06:54 UTC, erwango commented
LGTM, but it's expected that you generate a new batch of -pinctrl.dtsi files by yourself (so we can see if the result is as expected).
Instructions are available in the repo README. Please take care to use the correct SHA1

2023-05-22 06:54 UTC, erwango requested changes
Please generate new batch of files

2023-05-22 11:10 UTC, douardda commented
> 



> LGTM, but it's expected that you generate a new batch of -pinctrl.dtsi files by yourself (so we can see if the result is as expected).

Ok, it was not clear to me whether the newly generated dtsi files were expected with such a MR (so my comment "If accepted, dtsi files will have to be regenerated in a following PR") 

> Instructions are available in the repo README. Please take care to use the correct SHA1 and put this in a new commit.

I suppose "use the correct SHA1" is the sha1 mentioned in each `stm32cube/stm32xxx/README` file, right?
I realise I missed the README file in the `scripts/` directory, where all this is actually documented :-) (maybe a link from the top "repo README" file would help?)

2023-05-22 13:18 UTC, erwango commented
SHA1, is the one provided in `dts/README.rst`.
There are actually some lines in https://github.com/zephyrproject-rtos/hal_stm32#dtsi-files, but this can be improved and suggestions are welcome.

2024-05-03 15:13 UTC, erwango commented
I'm closing this PR due to inactivity. Please reopen if required.

2024-05-03 15:13 UTC, closed without merging