Stm32h503  does not enable the driver if instance is not present
zephyrproject-rtos/hal_stm32 pull request #181
Opened 2023-11-16 12:15 UTC by FRASTM

The stm32h503 soc does not embed delayblock (DLYB) or SAI block or DCACHE instances.
Consequently the corresponding drivers should be included.

2023-11-16 12:52 UTC, erwango requested changes
Please provide ST internal reference and document fix in README file

2023-11-17 08:14 UTC, FRASTM commented
Updating the stm32cube/stm32h5xx/README

2023-11-17 08:22 UTC, erwango approved these changes

2023-11-17 08:25 UTC, gautierg-st approved these changes

2023-11-17 09:58 UTC, merged