stm32cube: Update STM32Cube packages
zephyrproject-rtos/hal_stm32 pull request #183
Opened 2023-11-20 12:51 UTC by ajarmouni-st

These patches should be applied on top of PR https://github.com/zephyrproject-rtos/hal_stm32/pull/182

New batch of stm32cube package updates:
  - update stm32l4 to cube version  V1.18.0
  - update stm32f7 to cube version V1.17.1
  - update stm32wb to cube version V1.17.3
  - update stm32f1 to cube version V1.8.5
  - update stm32h7 to cube version V1.11.1
  - update stm32wba to cube version V1.1.1

An update of lib/stm32/stm32wb package to version V1.17.3

2023-11-20 14:01 UTC, erwango requested changes

2023-11-20 14:01 UTC, erwango commented on stm32cube/stm32h7xx/README
> +   version v1.11.1
So, was it fixed in the end ?

2023-11-20 14:01 UTC, erwango commented on stm32cube/stm32wbaxx/CMakeLists.txt
> +# Copyright (c) 2020 STMicroelectronics
2023 should be kept

2023-11-21 10:12 UTC, FRASTM commented on stm32cube/stm32h7xx/README
> -    Read timestamp only when status flag is set in Tx descriptor.
if related to ST  Internal Reference: 157129 it is not yet fixed (see ST Internal Reference: 157128)

2023-11-21 10:15 UTC, FRASTM reviewed
else LGTM

2023-12-05 07:57 UTC, erwango approved these changes

2023-12-05 08:25 UTC, FRASTM approved these changes

2023-12-05 08:39 UTC, merged