lib: stm32wba: fix code formatting issues & typos
zephyrproject-rtos/hal_stm32 pull request #192
Opened 2024-01-12 08:39 UTC by ajarmouni-st

This patch fixes code formatting issues & typos in the STM32WBA BLE library.

2024-01-12 09:55 UTC, erwango requested changes
Otherwise LGTM; Thanks

2024-01-12 09:55 UTC, erwango commented on lib/stm32wba/hci/README
Please add the following in patch list section:
   *Changes from official delivery:
    -dos2unix applied
    -trailing white spaces removed

2024-01-16 08:35 UTC, erwango approved these changes

2024-01-16 09:12 UTC, gautierg-st approved these changes

2024-01-16 09:20 UTC, merged