STM32WBA 1.3.1 Cube FW Updates Integration
zephyrproject-rtos/hal_stm32 pull request #214
Opened 2024-05-31 12:42 UTC by asm5878

Integration of HAL/LL/BLE updates from STM32WBA Cube FW 1.3.1

2024-05-31 13:30 UTC, erwango commented on stm32cube/stm32wbaxx/CMakeLists.txt
> +# Copyright (c) 2020 STMicroelectronics
Not required, remove this change

2024-05-31 13:30 UTC, erwango commented on stm32cube/stm32wbaxx/README
> +--> please check that the following list is still valid:
Remove this line

2024-05-31 13:30 UTC, erwango commented on lib/stm32wba/hci/README
> +--> please check that the following list is still valid:
Remove this line

2024-05-31 13:32 UTC, erwango commented on stm32cube/common_ll/README.rst
> +stm32wbxx       1.19.0
@marwaiehm-st Can you verify this is correct ?

2024-05-31 13:34 UTC, erwango commented on lib/stm32wba/hci/app_conf.h
> +#define RADIO_SW_LOW_INTR_PRIO              (14)           /* 2.4GHz RADIO low ISR priority */
Only this change is explained in the README.
Ideally provide one commit per change.

2024-05-31 13:34 UTC, erwango commented on zephyr/module.yml
> +    url: https://github.com/STMicroelectronics/STM32CubeWBA/raw/v1.3.1/Middlewares/ST/STM32_WPAN/ble/stack/lib/stm32wba_ble_stack_llo.a
Let's make it a dedicated commit

2024-06-05 12:46 UTC, asm5878 commented
Branch updated with the suggested changes.
Could you please review, thanks!

2024-06-05 14:20 UTC, erwango requested changes
One last minor change and this will be fine to me

2024-06-05 14:20 UTC, erwango commented on lib/stm32wba/hci/pta.h
Please also add this file in `lib/stm32wba/hci/README`

2024-06-06 09:52 UTC, asm5878 commented on lib/stm32wba/hci/pta.h
PR updated with latest suggested modification.
Could you please review? Thanks

2024-06-06 11:16 UTC, erwango approved these changes

2024-06-06 11:34 UTC, marwaiehm-st commented on lib/stm32wba/hci/linklayer_plat.h
> +#endif /* LINKLAYER_PLAT_H */
To avoid this you should add newline at end of the file

2024-06-06 11:35 UTC, marwaiehm-st commented on lib/stm32wba/hci/ll_sys.h
> +#endif /* LL_SYS_H */
Same

2024-06-06 11:35 UTC, marwaiehm-st commented on lib/stm32wba/hci/ll_sys_cs.c
> +}
same

2024-06-06 11:35 UTC, marwaiehm-st commented on lib/stm32wba/hci/pta.h
> +#endif /* PTA_H_ */
Same

2024-06-06 11:39 UTC, marwaiehm-st commented on stm32cube/stm32wbaxx/drivers/include/stm32wbaxx_hal.h
> +
Remove the space

2024-06-06 11:51 UTC, marwaiehm-st commented on lib/stm32wba/hci/ll_sys_startup.c
> +}
same

2024-06-06 11:51 UTC, marwaiehm-st commented on lib/stm32wba/hci/ll_sys_startup.h
> +#endif /* LL_SYS_STARTUP_H */
same

2024-06-06 12:03 UTC, gautierg-st requested changes
Only one file to remove + @marwaiehm-st comments, otherwise LGTM

2024-06-06 15:37 UTC, asm5878 commented
Dear All,
Here my new iteration.
Thanks for your feedback

2024-06-06 16:04 UTC, marwaiehm-st commented
LGTM

2024-06-06 16:17 UTC, marwaiehm-st approved these changes

2024-06-07 07:06 UTC, gautierg-st approved these changes

2024-06-07 07:25 UTC, erwango approved these changes

2024-06-07 07:25 UTC, merged