stm32h7: fix TX timestamp check
zephyrproject-rtos/hal_stm32 pull request #220
Opened 2024-06-27 15:04 UTC by kartben

It looks like the original code was a bad copy-paste from H5 HAL. ETH_DMATXDESC_LS and ETH_DMATXDESC_TTSS are flags from the DESC0 register. This allows to effectively et the TX timestamp properly when there is one.

2024-06-27 15:51 UTC, erwango requested changes
I'm fine with the change, but please:
- Update README file (https://github.com/zephyrproject-rtos/hal_stm32/blob/d12e21e35d8d33c5fdf711d1a1c07f38c9295f70/stm32cube/stm32f7xx/README#L37)
- Open a ticket in official HAL repo to follow up the fix

2024-09-02 14:16 UTC, erwango commented
@marwaiehm-st Since @kartben is busy, would you mind taking over this change ?

2024-09-02 15:27 UTC, marwaiehm-st commented
> @marwaiehm-st Since @kartben is busy, would you mind taking over this change ?

Ok

2024-09-04 13:44 UTC, erwango commented
> This PR is replaced by #232

Thanks @marwaiehm-st.
@kartben we'll close current issue to make topic moving forward, if you don't mind.

2024-09-04 13:44 UTC, closed without merging