Update pincrtl-dtsi files for all stm32 family
zephyrproject-rtos/hal_stm32 pull request #224
Opened 2024-07-30 14:35 UTC by djiatsaf-st

Some important changes have been made

1. In **modules/hal/stm32/scripts/genpinctrl/stm32-pinctrl-config.yaml** : 
Modify the yaml config file  to add "very-high-speed"  slew-rate for MCO signal

2.  In **modules/hal/stm32/dts/st** : 
     Update pincrtl*;dtsi files for all stm32 family

2024-08-02 07:19 UTC, erwango requested changes

2024-08-02 07:19 UTC, erwango commented on dts/README.rst
> +   f4ec11f00e762e37ffc4020f6d4f20d225bc061d
When generating new signals please re-use the same data base version than the last generation.
If a new database version is available, please perform the update in a new PR.

2024-08-02 14:07 UTC, erwango approved these changes

2024-09-10 12:39 UTC, mathieuchopstm reviewed
Files appear to be correct - however, commits should IMO be reworded:

```diff
- scripts: genpinctrl: add "very-high-speed" slew rate
+ scripts: genpinctrl: make MCO pins use "very-high-speed" slew rate
```

```diff
- dts: st: update files after edition
+ dts: regenerate pinctrl.dtsi with "very-high-speed" MCO
```

2024-09-12 09:41 UTC, gautierg-st approved these changes

2024-09-12 14:25 UTC, merged