Update HAL STM32
zephyrproject-rtos/hal_stm32 pull request #235
Opened 2024-09-27 06:40 UTC by gautierg-st

Update HAL STM32:
- C0: 1.1.0 -> 1.2.0
- F1: 1.8.5 -> 1.8.6
- F2: 1.9.4 -> 1.9.5
- F4: 1.28.0 -> 1.28.1
- G4: 1.5.2 -> 1.6.0
- H5: 1.2.0 -> 1.3.0
- H7RS: 1.0.0 -> 1.1.0
- U5: 1.5.0 -> 1.6.0
- WBA: 1.3.1 -> 1.4.1
- WB: 1.19.1 -> 1.20.0

2024-09-27 09:52 UTC, erwango requested changes

2024-09-27 09:52 UTC, erwango commented on stm32cube/stm32f2xx/README
> +--> please check that the following list is still valid:
Remove this line

2024-09-27 09:52 UTC, erwango commented on stm32cube/stm32h7rsxx/CMakeLists.txt
> -# Copyright (c) 2024 STMicroelectronics
Don't remove

2024-09-27 09:52 UTC, erwango commented on stm32cube/stm32u5xx/README
> -   Internal reference: 157095
I don't see this in the changes, was it delivered earlier ?

2024-09-27 09:52 UTC, erwango commented on lib/stm32wb/hci/README
> +--> please check that the following list is still valid:
Remove this line

2024-09-27 09:52 UTC, erwango commented on stm32cube/common_ll/README.rst
> +stm32wbaxx      1.4.1
Don't update wba

2024-09-27 14:31 UTC, gautierg-st commented on stm32cube/stm32f2xx/README
> +--> please check that the following list is still valid:
Done

2024-09-27 14:31 UTC, gautierg-st commented on stm32cube/stm32h7rsxx/CMakeLists.txt
> -# Copyright (c) 2024 STMicroelectronics
Done

2024-09-27 14:32 UTC, gautierg-st commented on lib/stm32wb/hci/README
> +--> please check that the following list is still valid:
Done

2024-09-27 14:32 UTC, gautierg-st commented on stm32cube/common_ll/README.rst
> +stm32wbaxx      1.4.1
Done

2024-09-30 12:59 UTC, erwango requested changes
Otherwise LGTM

2024-09-30 12:59 UTC, erwango commented on stm32cube/stm32f4xx/drivers/include/stm32f4xx_hal_conf.h
> +#endif /* HAL_ETH_LEGACY_MODULE_ENABLED */
Although we don't use this file we should probably follow this change for consistency.

2024-10-01 08:43 UTC, erwango approved these changes

2024-10-03 06:28 UTC, FRASTM approved these changes

2024-10-03 06:42 UTC, merged