Bring DTSI to the latest state and correct RTS/CTS pin configuration
zephyrproject-rtos/hal_stm32 pull request #238
Opened 2024-11-08 11:14 UTC by GeorgeCGV

The `genpinctrl.py` is corrected with a patch proposed by @mathieuchopstm, which allows you to catch template exceptions related to STM32C0.

The DTSI files are regenerated with pin open data [f4ec11](https://github.com/STMicroelectronics/STM32_open_pin_data/commit/f4ec11f00e762e37ffc4020f6d4f20d225bc061d).

A correction to RTS/CTS serial pins is added:
* CTS
   - remove `open-drain`
   - remove `pull-up` bias
* RTS
   - replace `open-drain` with `push-pull`
   - remove `pull-up` bias

The DTSI files are regenerated again to include RTS/CTS configuration changes.

2024-11-08 12:26 UTC, mathieuchopstm requested changes
Minor commit-related requests:
* please change first regeneration commit's title from `dts: st: regenerate all dtsi files` to `dts: st: regenerate all dtsi files with latest pindata`
* remove the skipped files list from `genpinctrl` commit's message
  * move it to `dts: st: regenerate all dtsi files with latest pindata` instead - with a header like `The following SoCs are skipped due to incompatibility with genpinctrl:`
  * I would also make the `genpinctrl` commit message more generic, something like:
```
The latest STM32 Open Pin Data revision contains SoC descriptors that
are not handled properly by genpinctrl yet. These files are parsed
properly but trigger an exception during the pinctrl template rendering.

Add exception logic around template rendering so that problematic SoC files
are skipped - with an error message - instead of crashing the script, which
would otherwise prevent regeneration of DTSI for *all* SoCs.

This allows us to keep updating the pinctrl DTSI for supported SoCs
even when new SoCs requiring genpinctrl updates are added to Pin Data.
```

Otherwise LGTM.

2024-11-08 13:37 UTC, mathieuchopstm approved these changes

2025-01-06 14:45 UTC, erwango commented
@GeorgeCGV Would you mind rebasing ?

2025-01-08 08:01 UTC, GeorgeCGV commented
@erwango @mathieuchopstm rebased and re-generated with currently used open pin data [3e9ade](https://github.com/STMicroelectronics/STM32_open_pin_data/commit/3e9ade95efd8e2331b8a53a500d73966f8f840ad) (_removes `stm32wba50keux`_).

Generation output:
```
Unexpected AF format: GPIO_AF2_rf (ip: STM32WL33_gpio_v1_0)
Skipping unsupported family STM32MP2.
Skipping unsupported family STM32N6.
Skipping unsupported family STM32U3.
Skipping unsupported family STM32WL3.
```

2025-01-08 09:47 UTC, mathieuchopstm approved these changes

2025-01-08 10:04 UTC, erwango approved these changes

2025-01-09 09:23 UTC, merged