stm32cube: Remove all STM32Cube release notes
zephyrproject-rtos/hal_stm32 pull request #240
Opened 2024-11-13 17:23 UTC by benothmn-st

Remove all STM32Cube release notes since the links to release notes of all components are relative paths to Cube package. So, they are broken links.
In the README file of the each cube folder, there is a link to the GitHub containing the release notes and all the STM32Cube details.

2024-11-14 09:18 UTC, erwango approved these changes
Approved, but DNM until v4.0.0 is released

2024-11-14 16:00 UTC, FRASTM approved these changes

2024-11-14 16:16 UTC, erwango requested changes
Back on this.

Removing release notes is ok, but since these files are updated automatically by series update scripts, the scripts should be updated to in order to not update the release notes from now on (otherwise they'll be back at next update).

So please update scripts additionally (in same PR but another commit).

2024-11-14 20:36 UTC, benothmn-st commented
@ABOSTM could you review this PR please?

2024-11-15 08:07 UTC, erwango requested changes

2024-11-15 08:07 UTC, erwango commented on scripts/serie_update.py
> -        self.copy_release_note()
That's part of it, but let's remove the method as well to minimize dead code.

2024-11-18 13:41 UTC, erwango approved these changes

2024-11-18 13:41 UTC, merged