HAL update
zephyrproject-rtos/hal_stm32 pull request #243
Opened 2024-12-03 14:40 UTC by gautierg-st

Update STM32 HAL:
- G4 to 1.6.1
- H5 to 1.4.0
- H7 to 1.12.0
- U0 to 1.2.0
- U5 to 1.7.0
- WB to 1.21.0

2024-12-03 16:20 UTC, erwango requested changes
Looks ok, but please remove STM32WB as there are some lib evolutions being prepared.

2024-12-04 07:53 UTC, gautierg-st commented
> Looks ok, but please remove STM32WB as there are some lib evolutions being prepared.

Done

2024-12-04 08:26 UTC, erwango approved these changes

2024-12-06 13:57 UTC, FRASTM approved these changes
thanks for updating the stm3232 hal

2024-12-06 14:14 UTC, merged