dts: add HRTIM pinctrl
zephyrproject-rtos/hal_stm32 pull request #87
Opened 2021-01-12 18:33 UTC by martinjaeger

Add options for high-resolution timer HRTIM to pinctrl-config and generate new pinctrl DTS files.

I know that the HRTIM peripheral is not yet supported by Zephyr, but I'm working on a driver and would like to use the pinctrl properly already.

2021-01-12 18:54 UTC, gmarull requested changes
@martinjaeger We usually add the config changes in one commit and the autogenerated content into another one to ease review process.

2021-01-12 19:09 UTC, martinjaeger commented
Ah, makes sense. Will fix that tomorrow.

2021-01-13 08:29 UTC, gmarull approved these changes

2021-02-04 16:07 UTC, luizvilla commented
Wonderful work @Martin!
We were looking for this. We'll implement and leave a comment here.

2021-02-04 16:43 UTC, martinjaeger commented
> Wonderful work @martinjaeger.
> We were looking for this. We'll implement and leave a comment here.

Great. Zephyr has feature freeze at the moment until v2.5 is released (scheduled for 12 February). After that we should probably get this PR in rather quickly.

In the meantime you can already add something like this to your board.dts as a workaround:
```
	soc {
		hrtim1: timers@40016800 {
			compatible = "st,stm32-timers";
			reg = <0x40016800 0x400>;
			clocks = <&rcc STM32_CLOCK_BUS_APB2 0x04000000>;
			interrupts = <67 0>, <68 0>, <69 0>, <70 0>, <71 0>, <72 0>, <73 0>, <74 0>;
			interrupt-names = "master", "tima", "timb", "timc", "timd", "time", "flt", "timf";
			status = "okay";
			label = "HRTIM_1";
		};

		/* required until hal_stm32 PR #87 is merged */
		pinctrl: pin-controller@48000000 {
			hrtim1_cha1_pa8: hrtim1_cha1_pa8 {
				pinmux = <STM32_PINMUX('A', 8, AF13)>;
			};

			hrtim1_cha2_pa9: hrtim1_cha2_pa9 {
				pinmux = <STM32_PINMUX('A', 9, AF13)>;
			};

			// ...
		};
	};
```

2021-02-16 13:55 UTC, galak commented
Is there a Zephyr side PR related to this?

2021-02-16 14:38 UTC, martinjaeger commented
> Is there a Zephyr side PR related to this?

Not yet. The driver is still work in progress.

It doesn't really make sense to use the HRTIM with the existing "simple" PWM API. The HRTIM is meant for motor driver and power converter applications with complementary PWM outputs. So we'll probably have to come up with a new API for that (half_bridge, sync_pwm, complementary_pwm or how ever it may be called).

2021-03-17 07:16 UTC, erwango approved these changes

2021-03-17 07:17 UTC, erwango commented
@martinjaeger Set as DNM waiting for a PR to use these in main Zephyr repo. Any objections ?

2021-03-17 07:27 UTC, gmarull commented
@erwango I think it is still fine to have definitions for peripherals that are currently not used in-tree. It can be helpful for people developing custom drivers.

2021-03-17 07:36 UTC, martinjaeger commented
> @erwango I think it is still fine to have definitions for peripherals that are currently not used in-tree. It can be helpful for people developing custom drivers.

I agree with @gmarull. The pinctrl driver is fully supported upstream and this PR only adds features to the pinctrl driver.

IMO we could even say that we generate pinctrl devicetree nodes that are defined in the original ST cube XML files in order to make out-of-tree driver development on top of pinctrl easier.

We don't need a dedicated commit upstream to update `west.yml`. But I think it would not harm anyone to just merge this here and get it in together with the next update.

2021-03-17 08:26 UTC, erwango commented
@gmarull, @martinjaeger Ok, it doesn't harm indeed and I don't have strong opinion otherwise.

> IMO we could even say that we generate all pinctrl devicetree nodes that are defined in the original ST cube XML files in order to make out-of-tree driver development on top of pinctrl easier.

I'm not particularly of favor of this as I prefer to have users and reviewers for each peripherals (as it seems to be that case here), and avoid generating blindly configurations that could be potentially broken. So I prefer this remains a case by case operation.

2021-03-17 08:27 UTC, erwango commented
@galak, this one is ready for merge.

2021-03-19 08:28 UTC, merged