Dev pincntrl stm32h7
zephyrproject-rtos/hal_stm32 pull request #96
Opened 2021-04-29 12:15 UTC by SpooniSpoon

MCO pin control definitions added for stm32h743vitx

2021-05-03 12:23 UTC, erwango requested changes
*-pinctrl.dsti files should not be modified manually.
Cf package README

2021-05-03 13:33 UTC, SpooniSpoon commented
> *-pinctrl.dsti files should not be modified manually.
> Cf package README

@erwango Thanks for the hint. Should I open an issue to add the MCO pin?

2021-05-03 14:04 UTC, erwango commented
> > *-pinctrl.dsti files should not be modified manually.
> > Cf package README
> 
> @erwango Thanks for the hint. Should I open an issue to add the MCO pin?

For this kind of change, we expect that the same PR provides:
- 1 commit adding the change to *.yaml file that provide pinctrl config
- 1 commit containing the *-pinctrl.dtsi generated with the new *.yaml files.

2021-05-04 06:13 UTC, SpooniSpoon commented
@erwango I had a look to the related *.ymal files. I am not familiar with the CubeMx *.xml files to fill out the regex expressions. Therefore I am not able to provide the requested changes. I will close the pull request and will stop to contribute to this sub project of zephyr.

2021-05-04 06:13 UTC, closed without merging

2021-05-04 06:57 UTC, erwango commented
@SpooniSpoon Thanks for the heads up and having had a try.
Anyway, moving MCO pin to device tree is in my plans, so I hope it could be available within next DV.